### ISSUE TITLE
'Execute job step' - DC executable is not platform dependend

### ISSUE THREAD

**Issue by ClaudiaPHI** [datacleaner/pdi-datacleaner#26]
In the dialog box for executing a DC job the prefilled textbox for DC executable is 'DataCleaner-console.exe'. But that it is not going to work for Unix users. 
Maybe we could prefill the textbox with the DC executable in accord with the platform they are using.

**Comment by kaspersorensen** [comment]
Even better - just use the same instance as already configured in the "Tools" menu - see #20
