### ISSUE TITLE
NPE when running plugin via Kitchen environment

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/pdi-datacleaner#35]
See forum: https://datacleaner.org/topic/1122/Help-with-Pentho-Kitchen-running-job-file-with-Execute-DataCleaner-job

Even includes a suggestion for a fix :)

**Comment by nashhoogwater** [comment]
I ran into the same problem and I needed it fixed, because the plugin doesn't work if you use kitchen. It is based on the comment left on the forum. A diff is included as attachment.

[fix-kitchen.zip](https://github.com/datacleaner/pdi-datacleaner/files/265079/fix-kitchen.zip)

**Comment by kaspersorensen** [comment]
Thank you very much @nashhoogwater ! I think it's very cool to see some contributions here. Maybe @ClaudiaPHI or @LosD can put it on their radar to check the patch sometime soon, since I'm no longer part of the core DC dev team)

**Comment by LosD** [comment]
It's added to the current sprint, so it should go be added for inclusion within the next two weeks.

Thanks @nashhoogwater! :)

**Comment by nashhoogwater** [comment]
Added a small additional fix to the same patch for a different issue al together. It is possible to add additional arguments to the DataCleaner execution. However if you use variables they are not substituted. I added a fix for this.

[fix-additional-argument-and-kitchen.zip](https://github.com/datacleaner/pdi-datacleaner/files/273493/fix-additional-argument-and-kitchen.zip)

**Comment by dobeslao** [comment]
I came here only to say thank folks, great job.
