### ISSUE TITLE
Pentaho datastores contain byte arrays in DC

### ISSUE THREAD

**Issue by ClaudiaPHI** [datacleaner/pdi-datacleaner#6]
While running a pentaho step as DC job the input file read by DC is a byte array. 
I ran this on Mac.

**Comment by kaspersorensen** [comment]
Not able to reproduce in PDI 5.4.0.0-128 on Windows.

Trying to download latest version (5.4.0.1-130) to see if there's any difference.

**Comment by kaspersorensen** [comment]
Also could not reproduce on latest!

**Comment by ClaudiaPHI** [comment]
I believe it happens for CSV datastores.

**Comment by kaspersorensen** [comment]
Confirmed on a CSV input step from pentaho:

![image](https://cloud.githubusercontent.com/assets/291450/9758850/4c8def3c-56e9-11e5-847b-fa4bab8d2c2d.png)
